import NavBar from './components/sample/nav-bar'
import './globals.css'

export const metadata = {
  title: 'Nextjs App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-gradient-to-br from-gray-400 via-gray-200 to-gray-400">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
